routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('home', function(){
//    return redirect('/');
//});


Route::get('/', function(){
    return view('welcome');
});


 Route::middleware('check-auth-user')->group(function () {

    Route::get('/products', 'ProductController@products')->name('getproduct');
    Route::get('sub-category/{id}', 'CategoryController@sub')->name('sub-category');
    Route::get('prod/{id}', 'CategoryController@prod');
    Route::resource('cart', 'CartController');
    Route::get('/confirm', 'CartController@confirm');
    Route::resource('/user', 'UserController');
    Route::resource('/order', 'OrderController');
    Route::get('/favourite/{product}','FavouriteController@add2')->name('product.favourite2');
    Route::get('pro/{id}','CategoryController@showproduct');
});


    Route::get('admin/login','AdminController@get_admin_login');
    Route::post('admin/login','AdminController@post_admin_login')->name('post-login');



Auth::routes();

Route::middleware('localization')->group(function () {
    Route::get('lang/{locale}', function ($locale){
        session()->put('locale',$locale);
        return redirect()->back();

    });

    Route::middleware('check-auth-admin')->group(function () {
        Route::get('/logout', 'AdminController@logout')->name('logout');
        Route::resource('product', 'ProductController');
        Route::get('child/{id}', 'CategoryController@childs');
    });

});

resources/views/alerts.blade.php
<div class="col-md-12 col-xs-12">
    {{--@if(request('msg'))--}}
    {{--<div class="flash alert alert-danger" align="center" role="alert">يجب تسجيل الدخول أولا حتى تتم العملية--}}
    {{--بنجاح--}}
    {{--</div>--}}
    {{--@endif--}}
    @if(session('error'))
        <div class="flash alert alert-danger" align="center" role="alert">{{ session('error') }}</div>
    @endif
    @if(session('success'))
        <div class="flash  alert-success" align="center" role="alert">{{ session('success') }}</div>
    @endif
    {{--@if(session('resend'))--}}
    {{--<div class="alert alert-danger" align="center" role="alert">--}}
    {{--{{ session('resend').' ... ' }}<a class="color-light-blue"--}}
    {{--href="{{ url('/resend_active_code/'.session('msg1')) }}">التفعيل--}}
    {{--الان</a>--}}
    {{--</div>--}}
    {{--@endif--}}
    @if ($errors->any())
        <div class="text-center alert alert-danger">
            <ul class="list-unstyled">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
</div>

resources/views/carts.blade.php
@extends('layouts.app')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>E-commerce grid</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>
                    <a>E-commerce</a>
                </li>
                <li class="active">
                    <strong>Products grid</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-4">


        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        {{--{{dd($cartItems)}}--}}

        <div class="row">

            @foreach($cartItems as $cartItem)
                <div class="col-md-3">
                    <div class="ibox">
                        <div class="ibox-content product-box">

                            <div class="product-imitation">
                                <img src="{{ asset('/public/product/'.$cartItem->attributes->image)}}"alt="no_pic_exist" class="img-responsive" >
                            </div>
                            <div class="product-desc">
                                <span class="product-price">
                                    {{$cartItem->price}}
                                </span>
                                                               {{--<a href="{{url("/sub-category/{$cartItem->category_id}")}}" class="text-muted" >{{$cartItem->category->parent->category_name}}</a>--}}
                                <p  class="product-name"> {{$cartItem->name}}</p>
                                {{--<span>{{$cartItem->quantity}}</span>--}}
                                <form method="get" action="{{route('cart.edit',$cartItem->id)}}">
                                    @csrf
                                    {{method_field('GET')}}
                                 <input type="number" style="color: #1a7bb9"value="{{$cartItem->quantity}}" name="quantity">
                                    <button type="submit" class="btn btn-success btn-sm">edit</button>
                                </form>
                                <div class="m-t text-right">

                                    <a href="{{url('product/'.$cartItem->id)}}" class="btn btn-xs btn-outline btn-primary">تفاصيل المنتج</a>
                                    {{--<a class="btn btn-success btn-sm" onclick="document.getElementById('favourite-form-{{$cartItem->id}}').submit();">--}}
                                        {{--<i class="fa fa-star"></i> {{$cartItem->favourite_to_users->count()}} </a>--}}

                                    <form id="favourite-form-{{$cartItem->id}}" action="{{url('favourite/'.$cartItem->id)}}" method="get" style="display: none">
                                    </form>
                                    <a href="{{route('cart.show',$cartItem->id)}}" class="btn btn-warning btn-sm"><i class="fa fa-cart-plus"></i> Remove cart</a>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach


        </div>
        <a type="button" class="btn-success btn-rounded confirm" href="{{url("/confirm")}}">تأكيد الطلب</a>
        </div>


@stop
@section("styles")
    <style>
        .product-imitation > img{
            height: 300px;
            width: 100%;

        }
        .product-imitation {
            padding:  0 ;
        }
        .col-lg-4  a{
            position: absolute;
            margin-top: 20px;
            width: 80px;
            text-align: center;

        }

        .confirm{
            margin:30px 550px 0px 200px;
            width: 200px;
            border-radius: 3px;
        }
    </style>
@endsection

resources/views/completerequest2.blade.php
@extends('layouts.app')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>E-commerce grid</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>
                    <a>E-commerce</a>
                </li>
                <li class="active">
                    <strong>Products grid</strong>
                </li>
            </ol>
        </div>
    </div>
{{--{{dd($user->id)}}--}}
    <div class="" style="margin: 40px 0px 20px;">
        @include('alerts')
        <form action="{{route('user.update',$user->id)}}" method="post" class="form-horizontal">
            {{csrf_field()}}
            {{method_field('PUT')}}
            <div class="form-group"><label class="col-sm-2 control-label">الاسم</label>

                <div class="col-sm-10"><input type="text" value="{{$user->name}}" class="form-control"></div>
            </div>

            <div class="form-group"><label class="col-sm-2 control-label">البريد الالكتروني</label>
                <div class="col-sm-10">
                    <input type="text" value="{{$user->email}}" class="form-control">
                </div>
            </div>
            <div class="form-group"><label class="col-sm-2 control-label">الخريطه</label></div>
            <div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">Location:</label>

                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="us3-address" />
                    </div>

                    <label class="col-sm-2 control-label" style="margin-right: 0px">Radius:</label>

                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="us3-radius" />
                    </div>
                </div>
            </div>

                <div  id="somecomponent" style="width: 800px; height: 400px;margin-right: 110px"></div>
                <div class="m-t-small">
                    <label class="p-r-small col-sm-1 control-label">Lat.:</label>

                    <div class="col-sm-3">
                        <input name="lat" type="text" class="form-control" style="width: 110px" id="us3-lat" />
                    </div>
                    <label class="p-r-small col-sm-2 control-label">Long.:</label>

                    <div class="col-sm-3">
                        <input name="long" type="text" class="form-control" style="width: 110px" id="us3-lon" />
                    </div>
                </div>

            <div>
                <button class="btn btn-success btn-rounded confirm">تأكيد</button>
            </div>

        </form>
    </div>

@stop
@section("styles")
    <style>
        .confirm
        {
            width: 100px;
            margin: 30px 550px 0px 200px;
            border-radius: 3px;

        }

    </style>
@endsection
@push('scripts')
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places&language=ar'></script>
    <script src="{{asset('assets/js/locationpicker.jquery.js')}}"></script>

    <script>
        $('#somecomponent').locationpicker();


    </script>
@endpush

resources/views/edit.blade.php
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Edit Product</title>

    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/bootstrap.rtl.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/font-awesome/css/font-awesome.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/css/animate.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/css/plugins/jasny/jasny-bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/css/plugins/datapicker/datepicker3.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/style1.css')}}" rel="stylesheet">
    <style>
        .ss{
            margin-right: 500px;
            float: left;
        }
        .lang{
            float: left;
            margin-left: 80px;
            margin-top: -43px;
            font-size: 18px;

        }
        #arabic
        {
            color: red;
            border-left: 2px solid #1b6d85;
            padding: 0 .5rem;
        }
        #en
        {
            padding: 0 .5rem;
            color: #1b1b1b;

        }

    </style>

</head>

<body class="top-navigation">

<div id="wrapper">
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom white-bg">
            <nav class="navbar navbar-static-top" role="navigation">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                        <i class="fa fa-reorder"></i>
                    </button>
                    <a href="#" class="navbar-brand">Inspinia</a>
                </div>
                <div class="navbar-collapse collapse" id="navbar">

                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <a class="ss" href="#" onclick="document.getElementById('logout-form1').submit();">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>
                    <form id="logout-form1" action="{{ route('logout') }}" method="get" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </div>
                <div class="lang">
                    <span> <a id="arabic" href="{{url('lang/ar')}}">عربي</a></span>
                    <span> <a id="en" href="{{url('lang/en')}}">EN</a></span>
                </div>
            </nav>
        </div>
    <div class="ibox-content">
@include('alerts')

        <form action="{{route('product.update',$model->id)}}" method="post"  class="form-horizontal" enctype="multipart/form-data">
            {{csrf_field()}}
            {{method_field('PUT')}}
            <div class="form-group"><label class="col-sm-2 control-label">{{__('message.product')}}</label>

                <div class="col-sm-10"><input type="text"  name="name" class="form-control" value="{{$model->name}}"></div>
            </div>

            <div class="form-group"><label class="col-sm-2 control-label">{{__('message.category')}}</label>
                <div class="col-sm-10">
                    <select class="form-control m-b"   name="category_name" id="mainCategory">
                        @foreach( $maincats as $maincat )
                            <option value="{{$maincat->id}}" {{( $maincat->id == $model->category->parent->id ) ? "selected":""}} >{{$maincat->category_name}}</option>
                        @endforeach
                    </select>
                </div>
{{--{{ dd($branchcat->id/, $model->category_id ) }}--}}
            </div>
            <div class="form-group"><label class="col-sm-2 control-label">{{__('message.branch')}}</label>
                <div class="col-sm-10">

                    <select class="form-control m-b"  id="branch"   name="category_name1">

                        @foreach( $branchcats as $branchcat )
                            <option value="{{$branchcat->id}}" {{( $branchcat->id == $model->category_id ) ? "selected":""}} >{{$branchcat->category_name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="form-group"><label class="col-sm-2 control-label">{{__('message.image')}}</label>

                    <div class="col-sm-10">
                        <input type="file" name="pic" class="form-control">
                        <img src="{{ asset('/public/product/'.$model->image) }}" style="height: 50px">
                    </div>
                </div>

            </div>
            <div class="form-group"><label class="col-sm-2 control-label">{{__('message.price')}}</label>

                <div class="col-sm-10"><input type="text" name="price" class="form-control" value="{{$model->price}}"></div>
            </div>


            <div class="form-group"><label class="col-sm-2 control-label">{{__('message.show')}}</label>
                <div class="col-sm-10">

                    <label>
                        <input type="radio" value="not_hide" {{($model->hide=="not_hide") ? "checked":""}} id="" name="radio"> نعم
                    </label>
                    <label>
                        <input type="radio" value="hide" {{($model->hide=="hide") ? "checked":""}} name="radio"> لا
                    </label>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>{{__('message.description')}}</h3>
                            <div class="ibox-tools">
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>

                            </div>
                        </div>
                        <div class="ibox-content no-padding">

                            <textarea name="description" class="summernote" class="form-group">
                                {{$model->description}}
                            </textarea>

                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group"><label class="col-sm-2 control-label">{{__('message.addition')}}</label>
                @foreach($additions as $addition)
                    <input type="checkbox" {{(in_array($addition->id, $ss))?"checked":""}} value="{{$addition->id}}" name="addition_name[]">
                        {{$addition->name}}
                @endforeach
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary btn-rounded bg-success">
                    {{__('message.submit')}}
                </button>
            </div>
        </form>
    </div>
{{--@stop--}}
{{--@push('scripts')--}}
    <script src="{{asset('assets/js/plugins/summernote/summernote.min.js')}}"></script>
<script>

    $(document).ready(function() {

            $('.summernote').summernote();

        $("#mainCategory").change(function (e) {
            e.preventDefault();

            var catId = $(this).val();
            // console.log(catId)
            // let data = {catId}
            axios.get('{{url('child')}}'+'/' + catId)
                .then(function (response) {
                    console.log(response.data.status);

                    if (response.data.status == true){
                        // var tt = "" ;
                        $("#branch").empty().append(response.data.data)

                    }



                })
            // .catch(function (error) {
            //     console.log(error);
            // })
            // .then(function () {
            //     // always executed
            // });



        });

    })
</script>
{{--@endpush--}}
@push('styles')
    <link href="{{asset('assets/css/css/plugins/summernote/summernote.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/css/plugins/summernote/summernote-bs3.css')}}" rel="stylesheet">

@endpush

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    hello
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/loginadmin.blade.php
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>تسجيل الدخول</title>

    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/font-awesome/css/font-awesome.css')}}" rel="stylesheet">

    <link href="{{asset('assets/css/animate.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/style.css')}}" rel="stylesheet">

</head>

<body class="gray-bg">
<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        @include('alerts')
        <div>

            <h1 class="logo-name">IN+</h1>

        </div>
        <h3>ADMIN LOGIN+</h3>
        <form method="post" class="m-t" role="form" action="{{route('post-login')}}">
            @csrf
            <div class="form-group">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" placeholder="Username" value="{{ old('email') }}" required autocomplete="email" autofocus>
                @error('email')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <input  placeholder="Password" id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">
                @error('password')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

            {{--<a href="#"><small>Forgot password?</small></a>--}}
            {{--<p class="text-muted text-center"><small>Do not have an account?</small></p>--}}
            {{--<a class="btn btn-sm btn-white btn-block" href="register.html">Create an account</a>--}}
        </form>

    </div>
</div>

<!-- Mainly scripts -->
<script src="{{asset('assets/js/jquery-3.1.1.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>

</body>

</html>

resources/views/orderdetails.blade.php
@extends('layouts.app')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>E-commerce grid</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>
                    <a>E-commerce</a>
                </li>
                <li class="active">
                    <strong>Products grid</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-4">


        </div>
    </div>
{{--{{dd($order)}}--}}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title ">
                    <div class="row">
                        <div class="col-lg-8">
                            <h5 style="font-size: 30px"> تفاصيل الطلب رقم {{$order->id}}</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="img text-center" >
                            <div class="row">
                                <div class="col-lg-9">
                                    <div class="ibox float-e-margins">
                                        <div class="col-sm-12">
                                            <div class="col-sm-4"><h4>اسم العميل </h4></div>
                                            <div class="col-sm-8"><p>{{$order->user->name}} </p></div>
                                        </div>
                                        <div class="col-sm-12">
                                            <div class="col-sm-4"><h4>طريقه الدفع</h4></div>
                                            <div class="col-sm-8"><p>{{$order->payment_way}}</p></div>
                                        </div>
                                        <div class="col-sm-12">
                                            <div class="col-sm-4"><h4> القيمه المضافه </h4></div>
                                            <div class="col-sm-8"><p>{{$order->add_value}}</p></div>
                                        </div>
                                        <div class="col-sm-12">
                                            <div class="col-sm-4"><h4>  المبلغ المطلوب </h4></div>
                                            <div class="col-sm-8"><p>{{$order->net}}</p></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
























@stop
@section("styles")
            <style>
            </style>
@endsection

resources/views/prod.blade.php
@extends('layouts.app')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>E-commerce grid</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>
                    <a>E-commerce</a>
                </li>
                <li class="active">
                    <strong>Products grid</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-4">
            <a type="button" href="{{route('product.create')}}" class="btn-rounded btn-success " >Add </a>

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            @foreach($cats as $cat)
                @foreach( $cat->product as $i )
                <div class="col-md-3">
                    <div class="ibox">
                        <div class="ibox-content product-box">

                            <div class="product-imitation">
                                <img src="{{ asset('/public/product/'.$i->image) }}"alt="no_pic_exist" class="img-responsive" >
                            </div>
                            <div class="product-desc">
                                <span class="product-price">
                                    {{$i->price}}
                                </span>
                                <p href="{{url("/sub-category/{$i->category_id}")}}" class="text-muted" >{{$cat->parent->category_name}}</p>
                                <p  class="product-name"> {{$i->name}}</p>
                                <div class="small m-t-xs">
                                    {{$i->description}}
                                </div>
                                <div class="m-t text-right">

                                    <a href="{{url('product/'.$i->id)}}" class="btn btn-xs btn-outline btn-primary">تفاصيل المنتج</a>
                                    <a href="{{url("/product/{$i->id}/edit")}}" class="btn btn-xs btn-outline  btn-warning">Edit </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            @endforeach
        </div>
    </div>


@stop
@section("styles")
    <style>
        .product-imitation > img{
            height: 300px;
            width: 100%;

        }
        .product-imitation {
            padding:  0 ;
        }
        .col-lg-4  a{
            position: absolute;
            margin-top: 20px;
            width: 80px;
            text-align: center;

        }
    </style>
@endsection

resources/views/show.blade.php
@extends('layouts.app')

@section('content')



        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-10">
                <h2>E-commerce product detail</h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="{{route('product.index')}}">Home</a>
                    </li>
                    <li>
                        <a>E-commerce</a>
                    </li>
                    <li class="active">
                        <strong>Product detail</strong>
                    </li>
                </ol>
            </div>
            <div class="col-lg-2">

            </div>
        </div>

        <div class="wrapper wrapper-content animated fadeInRight">

            <div class="row">
                <div class="col-lg-12">

                    <div class="ibox product-detail">
                        <div class="ibox-content">

                            <div class="row">
                                <div class="col-md-5">


                                    <div class="product-images">

                                        <div>
                                            <div class="image-imitation">
                                                <img src="{{ asset('/public/product/'.$model->image) }}" >
                                            </div>
                                        </div>


                                    </div>

                                </div>
                                <div class="col-md-7">

                                    <h2 class="font-bold m-b-xs">
                                        {{$model->name}}
                                    </h2>

                                    <div class="m-t-md">
                                        <h2 class="product-main-price">{{$model->price}}  </h2>
                                    </div>
                                    <hr>

                                    <h4>Product description</h4>

                                    <div class="small text-muted">
                                        {!!$model->description!!}
                                    </div>

                                    <hr>

                                    <div>
                                        <div class="btn-group">


                                            <button class="btn btn-white btn-sm"><i class="fa fa-envelope"></i> Contact with author </button>
                                        </div>
                                    </div>



                                </div>
                            </div>

                        </div>

                    </div>

                </div>
            </div>

        </div>

   @stop
@section("styles")
    <style>
        .image-imitation > img{
            height: 100%;
            width: 100%;

        }
        .image-imitation {
            padding:  0px 0 ;
        }
    </style>
@endsection





<script>
    $(document).ready(function(){


        $('.product-images').slick({
            dots: true
        });

    });

</script>